### PR TITLE
GSoC Heat project pull request

### PR DESCRIPTION
**Pull request by sparshk**
The two classes Pieces and Table have been created. The Table class represents the chess board and the pieces. The Pieces class contains various methods such as getWSoldier(), getWBishop() etc. that return the respective image files to the assignTilePieceIcon() function of the sub-class TilePanel of the Table class.

### CODE REVIEW

**Comment by nkprince007** [comment]
The code lacks proper indentation and variable naming. Without which it is not acceptable.

**Review by naveenkumarsangi — CHANGES_REQUESTED** [review]
The code lacks proper indentation and variable naming. Without which it is not acceptable. Also the commit messages are pretty vague and unclear.

**Comment by naveenkumarsangi** [comment]
Also, running your code doesn't display the chess board as expected. So, I'm not even sure about the scope of this pull request.

**Comment by pandusonu2** [comment]
Why are we doing separate getW() and getB() We can just pass an argument for the color

**Comment by sparshk** [comment]
It's indented properly in my IDE. But when I upload it on repo, it loses it's indentation. I couldn't understand why.

**Comment by sparshk** [comment]
When you run the table class, it does display the chess board with the pieces in their positions.

**Comment by sparshk** [comment]
I'll make the other changes and get back to you soon.

**Comment by naveenkumarsangi** [comment]
Well, you should update the text panel on chess tab so that the pieces are displayed there in. Not in a different frame. About the indentation, you've mixed up tabs and spaces. To maintain consistency, follow whatever the other files are doing so.

**Comment by sparshk** [comment]
Okay. I'll update it. You've checked the chess board right?

**Pull request closed without merging**
